check chr names, avoid merging from one file

diff --git a/muvac b/muvac
--- a/muvac
+++ b/muvac
@@ -73,6 +73,7 @@ rundependencies () {
 	[[ $(bash -version | head -1 | perl -lane 'if ($_=~/version\s+4\.(\d+)/i){if($1>=3){print 1}else{print 0}}else{print 0}') -eq 0 ]] && echo ":ERROR: dependency missing: bash 4.3" && return 1
 	[[ ! -s /usr/include/python2.7/Python.h ]] && echo ":ERROR: dependency missing: python-dev" && return 1
 	[[ $(java -version 2>&1 | head -1 | grep -c '1.8') -ne 1 ]] && echo ":ERROR: dependency missing: java 8" && return 1
+	[[ $(perl -e 'use List::MoreUtils' &> /dev/null; echo $?) -gt 0 ]] && echo ":ERROR: dependency missing: perl List::MoreUtils" && return 1
 	return 0
 }
 
@@ -826,6 +827,13 @@ if [[ $norecal -eq 0 ]]; then
 	[[ $? -gt 0 ]] && echo ":ERROR: indel error correction failed" && return 1
 
 	echo ":INFO: base recalibration"
+	if [[ $(md5sum $genome | cut -d ' ' -f 1) != '71eddfce325a99cfb8c6d67e1a4508a4' ]] || [[ ! -s $genome.vcf.gz ]] || [[ ! -s $genome.vcf.gz.tbi ]]; then
+		echo ":INFO: compressing and indexing dbsnp"
+		${BASH_ALIASES[bgzip]} -f -@ $threads < $genome.vcf > $genome.vcf.gz
+		[[ $? -gt 0 ]] && echo ":ERROR: compressing dbsnp failed" && return 1
+		${BASH_ALIASES[tabix]} -f -p vcf $genome.vcf.gz
+		[[ $? -gt 0 ]] && echo ":ERROR: indexing dbsnp failed" && return 1
+	fi
 	cmd=()
 	for r in ${mapper[@]}; do
 		od=$outdir/errorcorrected/$r
@@ -1028,7 +1036,7 @@ if [[ $Smerge -eq 0 ]]; then
 				${BASH_ALIASES[tabix]} -f -p vcf $v.gz
 				[[ $? -gt 0 ]] && echo ":ERROR: vcf indexing for $r failed" && return 1
 			done
-			if [[ $(ls $o*.vcf.gz | grep -v merged | wc -l) -gt 0 ]]; then
+			if [[ $(ls $o*.vcf.gz | grep -v merged | wc -l) -gt 1 ]]; then
 				${BASH_ALIASES[bcftools]} merge --print-header --force-samples $(ls $o*.vcf.gz | grep -v merged) > $o.merged.vcf
 				[[ $? -gt 0 ]] && echo ":ERROR: vcf header merge for $r failed" && return 1
 				sed -i '$ d' $o.merged.vcf
@@ -1044,7 +1052,7 @@ if [[ $Smerge -eq 0 ]]; then
 		for f in ${m[@]}; do
 			o=$(basename $f)
 			o=$od/${o%.*}
-			if [[ $(ls $o*.vcf | grep -v merged | head -1 | perl -F'\.' -ane '{print $F[-2]}' | wc -l) -gt 0 ]]; then
+			if [[ $(ls $o*.vcf.gz | grep -v merged | wc -l) -gt 1 ]] && [[ -s $o.merged.vcf ]]; then
 				export caller=$(ls $o*.vcf | grep -v merged | head -1 | perl -F'\.' -ane '{print $F[-2]}')
 				perl -lane '$F[7]=join(";",grep {$_=~s/^$ENV[caller]://; } split /;/,$F[7]); $F[7]="." unless $F[7]; print join "\t",@F' $o.merged.vcf > $o.merged.reduced.vcf
 				[[ $? -gt 0 ]] && echo ":ERROR: vcf merge reduction for $r failed" && return 1
@@ -1093,6 +1101,13 @@ if [[ $noanno -eq 0 ]]; then
 	fi
 
 	echo ":INFO: variant annotation - snpeff"
+	if [[ $(md5sum $genome | cut -d ' ' -f 1) != '71eddfce325a99cfb8c6d67e1a4508a4' ]] || [[ ! -s $genome.vcf.gz ]] || [[ ! -s $genome.vcf.gz.tbi ]]; then
+		echo ":INFO: compressing and indexing dbsnp"
+		${BASH_ALIASES[bgzip]} -f -@ $threads < $genome.vcf > $genome.vcf.gz
+		[[ $? -gt 0 ]] && echo ":ERROR: compressing dbsnp failed" && return 1
+		${BASH_ALIASES[tabix]} -f -p vcf $genome.vcf.gz
+		[[ $? -gt 0 ]] && echo ":ERROR: indexing dbsnp failed" && return 1
+	fi
 	cmd=()
 	for r in ${mapper[@]}; do
 		id=$outdir/vcf/$r
@@ -1473,7 +1488,7 @@ else
 	excode=${PIPESTATUS[0]}
 fi
 if [[ $excode -gt 0 ]]; then
-	tac tmp.log | awk '!/^(\t|:ERROR:|Command|bash:)/{print; exit}'
+	tac $log | awk '!/^(\s*$|\t|:ERROR:|Command|bash:|java|#+\s*ERROR\s*---)/{print; exit}'
 	tail -1 $log
 	echo ":ERROR: pipeline failed" | tee -a $log
 	exit 1
